language: nodejs

node_js:
  - "5.11"

branches:
  only:
    - master

before_install:
  - rvm install 2.5.1
  - rvm use 2.5.1
  - . $HOME/.nvm/nvm.sh && nvm install 6.1 && nvm use 6.1
  - bundle check || bundle install

install:
  - npm install -g firebase-tools 
  - gem install bundler

before_script:
  - bundle check || bundle install

script:
  - echo "Building and Testing"
  - bundle exec jekyll build
  # - bundle exec htmlproofer ./_site

after_success:
  - echo "Deploying"
  - firebase deploy --token $FIREBASE_TOKEN