language: ruby

rvm:
  - 2.5.1

branches:
  only:
    - release
    - master
    - html-proofer

install:
  - gem install bundler
  - bundle check || bundle install

script:
  - echo "Building and Testing"
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site

deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  on:
    branch: release
