language: ruby

rvm:
  - 2.5.1

branches:
  only:
    - release
    - master

install:
  - nvm install 8.12 && nvm use 8.12
  - npm install -g firebase-tools 
  - gem install bundler
  - bundle check || bundle install

script:
  - echo "Building and Testing"
  - bundle exec jekyll build
  # - bundle exec htmlproofer ./_site

deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  on:
    branch: release
